import type { Activity, ItineraryDay, Trip } from '@/types'

export const SEED_TRIP: Omit<Trip, 'owner_id' | 'pin_hash'> = {
  id: 'trip-alps-2026',
  slug: 'alps-bavaria-2026',
  name: 'אלפים ובוואריה 2026',
  tagline: 'הרי אוסטריה, כפרים מהאגדות, וקסם בווארי',
  start_date: '2026-08-18',
  end_date: '2026-08-26',
  cover_emoji: '⛰️',
  cover_image_url: null,
  adults_count: 10,
  children_ages: [4, 6, 7, 9, 10, 12, 14, 16],
  travel_style: 'relaxed',
  kid_focused: true,
  nature_first: true,
  is_public: true,
  share_token: 'fam2026alps',
  destinations: [
    {
      id: 'd1',
      trip_id: 'trip-alps-2026',
      name: 'נמל התעופה מינכן',
      country: 'Germany',
      lat: 48.3538,
      lng: 11.7861,
      arrival_date: '2026-08-18',
      departure_date: '2026-08-18',
      accommodation_name: null,
      sort_order: 1,
    },
    {
      id: 'd2',
      trip_id: 'trip-alps-2026',
      name: 'פלכאו, אוסטריה',
      country: 'Austria',
      lat: 47.3419,
      lng: 13.3891,
      arrival_date: '2026-08-18',
      departure_date: '2026-08-24',
      accommodation_name: 'Sonnberg Ferienanlage',
      sort_order: 2,
    },
    {
      id: 'd3',
      trip_id: 'trip-alps-2026',
      name: 'מינכן, גרמניה',
      country: 'Germany',
      lat: 48.1351,
      lng: 11.582,
      arrival_date: '2026-08-24',
      departure_date: '2026-08-26',
      accommodation_name: 'Hotel Motel One München-City',
      sort_order: 3,
    },
  ],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const FLACHAU_HOTEL = { lat: 47.3419, lng: 13.3891 }
export const MUNICH_HOTEL = { lat: 48.1275, lng: 11.5979 }

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'act-hallstatt',
    trip_id: 'trip-alps-2026',
    title: 'Hallstatt Village Walk',
    title_he: 'טיול בכפר הלשטאט',
    description: "Wander through one of the world's most photographed villages — a UNESCO Heritage Site clinging to the edge of a turquoise lake.",
    description_he: 'טיול בכפר הנמנה עם היפים בעולם — אתר מורשת עולמית של אונסק"ו השוכן על גדות אגם תכלת.',
    emoji: '🏘️',
    location_name: 'Hallstatt',
    region: 'Upper Austria',
    country: 'Austria',
    lat: 47.5623,
    lng: 13.6493,
    google_maps_url: 'https://maps.google.com/?q=Hallstatt+Austria',
    website: 'https://www.hallstatt.net',
    youtube_url: 'https://www.youtube.com/watch?v=5jAGXkE_PZ8',
    waze_url: 'https://waze.com/ul?ll=47.5623,13.6493&navigate=yes',
    duration_minutes: 180,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: 'free',
    price_estimate: 'כניסה חינם. מכרה מלח: €34 מבוגר, €17 ילד',
    booking_required: false,
    booking_url: null,
    tips: 'הגיעו לפני 9:00 לפני ההמונים. חנו בחניון Lahn — חינם ו-10 דקות הליכה.',
    family_notes: 'מושלם לכל הגילאים. ילדים אוהבים את סיפור מכרה המלח. הביאו בגדי ים.',
    tags: ['scenic', 'kids', 'nature', 'UNESCO', 'lake', 'free'],
    images: [],
    google_rating: 4.9,
    google_review_count: 21400,
    tripadvisor_rating: 4.8,
    nearby_restaurants: [{ name: 'Seehotel Grüner Baum', type: 'Austrian', distance_km: 0.2 }],
    nearby_attractions: [{ name: 'Salt Mine', type: 'Historic', distance_km: 1.8 }],
    is_rainy_day_alt: false,
    phase: 'austria',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-dachstein',
    trip_id: 'trip-alps-2026',
    title: 'Dachstein Cable Car & Ice Cave',
    title_he: 'רכבל דכשטיין ומערת הקרח',
    description: 'Soar to 2,700m on the Dachstein Seilbahn for breathtaking glacier views. The Mammut Ice Palace is a surreal world of illuminated ice sculptures.',
    description_he: 'עלו ל-2,700 מטר ברכבל דכשטיין. ארמון הקרח "ממות" בתוך הקרחון — פסלי קרח מוארים שהילדים ישתגעו עליהם.',
    emoji: '🚡',
    location_name: 'Obertraun',
    region: 'Upper Austria',
    country: 'Austria',
    lat: 47.5112,
    lng: 13.7137,
    google_maps_url: 'https://maps.google.com/?q=Dachstein+Seilbahn',
    website: 'https://www.dachstein-salzkammergut.at',
    youtube_url: 'https://www.youtube.com/watch?v=GqfFkukI4HI',
    waze_url: 'https://waze.com/ul?ll=47.5112,13.7137&navigate=yes',
    duration_minutes: 150,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'mixed',
    weather_suitability: 'any-weather',
    price_level: '€€',
    price_estimate: '€45 מבוגר, €22 ילד',
    booking_required: true,
    booking_url: 'https://www.dachstein-salzkammergut.at/tickets',
    tips: 'הזמינו מראש. בתוך המערה 0°C — הביאו שכבה חמה לכולם!',
    family_notes: 'מערת הקרח היא ההייליט — הצבעים מדהימים. מומלץ מגיל 4.',
    tags: ['adventure', 'kids', 'scenic', 'glacier', 'rainy day ok'],
    images: [],
    google_rating: 4.7,
    google_review_count: 8200,
    tripadvisor_rating: 4.6,
    nearby_restaurants: [{ name: 'Bergrestaurant Schönbergalpe', type: 'Mountain', distance_km: 0.1 }],
    nearby_attractions: [{ name: 'Hallstatt Village', type: 'Village', distance_km: 6 }],
    is_rainy_day_alt: true,
    phase: 'austria',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-salzburg',
    trip_id: 'trip-alps-2026',
    title: 'Salzburg Old Town & Fortress',
    title_he: 'העיר העתיקה של זלצבורג והמבצר',
    description: "Explore Mozart's birthplace with its magnificent baroque old town. The Hohensalzburg Fortress is Austria's largest fully preserved castle.",
    description_he: 'עיר הולדתו של מוצארט עם העיר העתיקה הבארוקית. מבצר הוהנזלצבורג — הטירה המשומרת הגדולה ביותר באוסטריה.',
    emoji: '🏰',
    location_name: 'Salzburg',
    region: 'Salzburg',
    country: 'Austria',
    lat: 47.8095,
    lng: 13.055,
    google_maps_url: 'https://maps.google.com/?q=Salzburg+Old+Town',
    website: 'https://www.salzburg.info',
    youtube_url: 'https://www.youtube.com/watch?v=dFPMTeVjgbI',
    waze_url: 'https://waze.com/ul?ll=47.8095,13.0550&navigate=yes',
    duration_minutes: 300,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'mixed',
    weather_suitability: 'any-weather',
    price_level: '€€',
    price_estimate: 'מבצר: €16 מבוגר, €9 ילד. טיול ברחוב — חינם',
    booking_required: false,
    booking_url: null,
    tips: 'קחו את הפוניקולר למבצר. צאו מוקדם — חנייה מאתגרת.',
    family_notes: 'ילדים מקבלים אודיוגייד מיוחד במבצר. גני מירבל נהדרים לריצה חופשית.',
    tags: ['history', 'kids', 'scenic', 'urban', 'culture'],
    images: [],
    google_rating: 4.8,
    google_review_count: 45000,
    tripadvisor_rating: 4.8,
    nearby_restaurants: [{ name: 'Augustiner Bräustübl', type: 'Beer hall', distance_km: 0.8 }],
    nearby_attractions: [{ name: 'Mirabell Gardens', type: 'Gardens', distance_km: 0.8 }],
    is_rainy_day_alt: true,
    phase: 'austria',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-mirabell',
    trip_id: 'trip-alps-2026',
    title: 'Mirabell Palace & Gardens',
    title_he: 'ארמון מירבל וגניו',
    description: "The baroque Mirabell Gardens are one of Salzburg's most beautiful spots, famous from The Sound of Music.",
    description_he: 'גני מירבל הבארוקיים — מפורסמים מסרט "The Sound of Music". ערוגות פרחים גיאומטריות ומזרקות יפהפיות.',
    emoji: '🌹',
    location_name: 'Salzburg',
    region: 'Salzburg',
    country: 'Austria',
    lat: 47.8044,
    lng: 13.0435,
    google_maps_url: 'https://maps.google.com/?q=Mirabell+Gardens+Salzburg',
    website: 'https://www.salzburg.info',
    youtube_url: 'https://www.youtube.com/watch?v=xrLtNcEMkBk',
    waze_url: 'https://waze.com/ul?ll=47.8044,13.0435&navigate=yes',
    duration_minutes: 60,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: 'free',
    price_estimate: 'חינם לגמרי',
    booking_required: false,
    booking_url: null,
    tips: 'הגנים פתוחים 24/7. הצילום הטוב ביותר בבוקר מוקדם.',
    family_notes: 'ילדים אוהבים לרוץ בין הערוגות ולטפס על פסלי הגמדים.',
    tags: ['scenic', 'free', 'kids', 'gardens'],
    images: [],
    google_rating: 4.7,
    google_review_count: 32000,
    tripadvisor_rating: 4.7,
    nearby_restaurants: [],
    nearby_attractions: [{ name: 'Hohensalzburg Fortress', type: 'Castle', distance_km: 1.2 }],
    is_rainy_day_alt: false,
    phase: 'austria',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-zell',
    trip_id: 'trip-alps-2026',
    title: 'Zell am See Boat Tour & Beach',
    title_he: 'סיור סירות וחוף זל אם זה',
    description: 'Glide across the impossibly blue Zellersee on a wooden excursion boat, then relax on the sandy beach.',
    description_he: 'הפלגה על פני אגם זל התכלת בסירת עץ, ואחר כך — חוף חולי עם מים רדודים לילדים.',
    emoji: '⛵',
    location_name: 'Zell am See',
    region: 'Salzburg Land',
    country: 'Austria',
    lat: 47.3244,
    lng: 12.7964,
    google_maps_url: 'https://maps.google.com/?q=Zell+am+See+boat',
    website: 'https://www.schifffahrt-zellamsee.at',
    youtube_url: 'https://www.youtube.com/watch?v=SVBV6GXHBWM',
    waze_url: 'https://waze.com/ul?ll=47.3244,12.7964&navigate=yes',
    duration_minutes: 210,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: '€€',
    price_estimate: 'סירה: €14 מבוגר, €7 ילד',
    booking_required: false,
    booking_url: null,
    tips: 'בוקר — מים שקטים ואור זהוב. קחו פדלו לילדים.',
    family_notes: 'חוף Strandbad מושלם לילדים קטנים — מים רדודים ומגרש משחקים.',
    tags: ['lake', 'scenic', 'kids', 'swimming', 'boat'],
    images: [],
    google_rating: 4.7,
    google_review_count: 3100,
    tripadvisor_rating: 4.6,
    nearby_restaurants: [{ name: 'Seewirt Dreilinden', type: 'Lakeside', distance_km: 0.5 }],
    nearby_attractions: [{ name: 'Kitzsteinhorn Glacier', type: 'Mountain', distance_km: 15 }],
    is_rainy_day_alt: false,
    phase: 'austria',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-kitzsteinhorn',
    trip_id: 'trip-alps-2026',
    title: 'Kitzsteinhorn Glacier',
    title_he: 'קרחון קיצשטיינהורן',
    description: "Austria's most accessible year-round glacier at 3,029m above Kaprun with panoramic views of 30+ peaks.",
    description_he: 'הקרחון הנגיש ביותר באוסטריה — 3,029 מטר מעל קפרון. נוף ל-30+ פסגות הרים.',
    emoji: '🏔️',
    location_name: 'Kaprun',
    region: 'Salzburg Land',
    country: 'Austria',
    lat: 47.1933,
    lng: 12.6866,
    google_maps_url: 'https://maps.google.com/?q=Kitzsteinhorn+Kaprun',
    website: 'https://www.kitzsteinhorn.at',
    youtube_url: 'https://www.youtube.com/watch?v=GUpB3nGRlQk',
    waze_url: 'https://waze.com/ul?ll=47.1933,12.6866&navigate=yes',
    duration_minutes: 240,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: '€€€',
    price_estimate: '€55 מבוגר, €28 ילד',
    booking_required: false,
    booking_url: null,
    tips: 'לכו רק ביום בהיר! בפסגה 5-10°C בקיץ.',
    family_notes: 'ילדים ישמחו לגעת בשלג אמיתי בקיץ!',
    tags: ['glacier', 'scenic', 'adventure', 'kids'],
    images: [],
    google_rating: 4.6,
    google_review_count: 5800,
    tripadvisor_rating: 4.5,
    nearby_restaurants: [{ name: 'Restaurant Gipfel', type: 'Mountain', distance_km: 0 }],
    nearby_attractions: [],
    is_rainy_day_alt: false,
    phase: 'austria',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-wolfgangsee',
    trip_id: 'trip-alps-2026',
    title: 'Lake Wolfgangsee Sunset',
    title_he: 'שקיעה באגם וולפגנגזה',
    description: 'St. Wolfgang sits on one of the most beautiful lakes in the Salzkammergut. Evening light turns the water gold and pink.',
    description_he: 'סנקט וולפגנג על אגם יפהפה. אור הערב הופך את המים לזהב ורוד — נוף לא נשכח.',
    emoji: '🏖️',
    location_name: 'St. Wolfgang',
    region: 'Upper Austria',
    country: 'Austria',
    lat: 47.7395,
    lng: 13.4465,
    google_maps_url: 'https://maps.google.com/?q=St+Wolfgang+Wolfgangsee',
    website: 'https://www.wolfgangsee.at',
    youtube_url: 'https://www.youtube.com/watch?v=bGlBbMkHN1Y',
    waze_url: 'https://waze.com/ul?ll=47.7395,13.4465&navigate=yes',
    duration_minutes: 90,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: 'free',
    price_estimate: 'חינם. חנייה €3/שעה',
    booking_required: false,
    booking_url: null,
    tips: 'השקיעה באוגוסט 19:00-20:00. חנו בחניון הראשי.',
    family_notes: 'קל ורגוע — מושלם אחרי יום פעיל. ילדים אוהבים להאכיל ברווזים.',
    tags: ['lake', 'scenic', 'free', 'sunset', 'relaxed'],
    images: [],
    google_rating: 4.6,
    google_review_count: 5600,
    tripadvisor_rating: 4.5,
    nearby_restaurants: [{ name: 'Weisses Rössl', type: 'Austrian', distance_km: 0.1 }],
    nearby_attractions: [],
    is_rainy_day_alt: false,
    phase: 'austria',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-flachau-toboggan',
    trip_id: 'trip-alps-2026',
    title: 'Flachau Summer Toboggan',
    title_he: 'מגלשת קיץ פלכאו',
    description: 'The Flachau summer toboggan run is a 1.3km alpine slide where you control your own speed.',
    description_he: 'מגלשת קיץ של פלכאו — 1.3 ק"מ שבה אתם שולטים במהירות. ההייליט של הטיול!',
    emoji: '🎿',
    location_name: 'Flachau',
    region: 'Salzburg Land',
    country: 'Austria',
    lat: 47.345,
    lng: 13.388,
    google_maps_url: 'https://maps.google.com/?q=Sommerrodelbahn+Flachau',
    website: 'https://www.flachau.com',
    youtube_url: 'https://www.youtube.com/watch?v=y_G0AhfAhbE',
    waze_url: 'https://waze.com/ul?ll=47.3450,13.3880&navigate=yes',
    duration_minutes: 120,
    difficulty: 'easy',
    recommended_ages: 'גיל 4+',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: '€',
    price_estimate: '€8 לרכיבה, צרור 5 רכיבות €32',
    booking_required: false,
    booking_url: null,
    tips: 'קנו צרור רכיבות — שווה הרבה יותר.',
    family_notes: 'אחד הדברים הכי כיפיים בטיול! כל הגילאים נהנים.',
    tags: ['kids', 'adventure', 'fun', 'local'],
    images: [],
    google_rating: 4.5,
    google_review_count: 1200,
    tripadvisor_rating: 4.4,
    nearby_restaurants: [],
    nearby_attractions: [],
    is_rainy_day_alt: false,
    phase: 'austria',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-chiemsee',
    trip_id: 'trip-alps-2026',
    title: 'Herrenchiemsee Palace Island',
    title_he: 'ארמון האי הרנכימזה',
    description: "Ludwig II's Versailles-inspired palace on an island in Bavaria's largest lake.",
    description_he: 'ארמון בהשראת ורסאי על אי בלב האגם הגדול ביותר של בוואריה — פלאי.',
    emoji: '🏝️',
    location_name: 'Chiemsee, Bavaria',
    region: 'Bavaria',
    country: 'Germany',
    lat: 47.8559,
    lng: 12.3989,
    google_maps_url: 'https://maps.google.com/?q=Herrenchiemsee+Palace',
    website: 'https://www.herrenchiemsee.de',
    youtube_url: 'https://www.youtube.com/watch?v=XMkBUArFpV4',
    waze_url: 'https://waze.com/ul?ll=47.8559,12.3989&navigate=yes',
    duration_minutes: 210,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'mixed',
    weather_suitability: 'any-weather',
    price_level: '€€',
    price_estimate: '€10 מבוגר + €5.50 מעבורת',
    booking_required: false,
    booking_url: null,
    tips: 'עצירה מושלמת בדרך מאוסטריה למינכן.',
    family_notes: 'ילדים נהנים מהמעבורת ומהגינות הגדולות.',
    tags: ['history', 'kids', 'palace', 'boat', 'Bavaria'],
    images: [],
    google_rating: 4.7,
    google_review_count: 12000,
    tripadvisor_rating: 4.7,
    nearby_restaurants: [{ name: 'Inselrestaurant', type: 'Bavarian', distance_km: 0.1 }],
    nearby_attractions: [],
    is_rainy_day_alt: true,
    phase: 'munich',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-englischergarten',
    trip_id: 'trip-alps-2026',
    title: 'English Garden & River Surfers',
    title_he: 'הגן האנגלי וגולשי הנהר',
    description: "Munich's enormous park features surfers on the artificial wave at Eisbachwelle — completely unique in the world.",
    description_he: 'הפארק הענק של מינכן עם גולשים על גל מלאכותי בנהר — תופעה ייחודית בעולם!',
    emoji: '🌳',
    location_name: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    lat: 48.1642,
    lng: 11.605,
    google_maps_url: 'https://maps.google.com/?q=Eisbachwelle+Munich',
    website: 'https://www.muenchen.de',
    youtube_url: 'https://www.youtube.com/watch?v=DJHKBt_AYaQ',
    waze_url: 'https://waze.com/ul?ll=48.1642,11.6050&navigate=yes',
    duration_minutes: 150,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: 'free',
    price_estimate: 'חינם',
    booking_required: false,
    booking_url: null,
    tips: 'הגולשים פעילים בעיקר אחר הצהריים.',
    family_notes: 'ילדים נדהמים מהגולשים בנהר העירוני!',
    tags: ['free', 'kids', 'nature', 'urban', 'Munich'],
    images: [],
    google_rating: 4.7,
    google_review_count: 38000,
    tripadvisor_rating: 4.7,
    nearby_restaurants: [{ name: 'Chinesischer Turm Biergarten', type: 'Beer garden', distance_km: 0.8 }],
    nearby_attractions: [],
    is_rainy_day_alt: false,
    phase: 'munich',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-deutsches',
    trip_id: 'trip-alps-2026',
    title: 'Deutsches Museum',
    title_he: 'המוזיאון הגרמני למדע',
    description: "One of the world's largest science museums with 73,000+ exhibits — aviation, ships, chemistry, and more.",
    description_he: 'אחד ממוזיאוני המדע הגדולים בעולם — 73,000+ תצוגות. ילדים משתגעים!',
    emoji: '🔬',
    location_name: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    lat: 48.13,
    lng: 11.5837,
    google_maps_url: 'https://maps.google.com/?q=Deutsches+Museum+Munich',
    website: 'https://www.deutsches-museum.de',
    youtube_url: 'https://www.youtube.com/watch?v=pQMJyp2FURU',
    waze_url: 'https://waze.com/ul?ll=48.1300,11.5837&navigate=yes',
    duration_minutes: 240,
    difficulty: 'easy',
    recommended_ages: 'גיל 5+',
    activity_type: 'indoor',
    weather_suitability: 'any-weather',
    price_level: '€€',
    price_estimate: '€18 מבוגר, €8 ילד. מתחת לגיל 6 חינם',
    booking_required: true,
    booking_url: 'https://shop.deutsches-museum.de',
    tips: 'קנו כרטיסים אונליין. התחילו מאולם הספינות — הצוללת מדהימה.',
    family_notes: 'המוזיאון האידיאלי ליום גשום. ילדים 6-14 בגן עדן.',
    tags: ['kids', 'indoor', 'science', 'rainy day', 'Munich'],
    images: [],
    google_rating: 4.5,
    google_review_count: 28000,
    tripadvisor_rating: 4.5,
    nearby_restaurants: [{ name: 'Museumsgaststätte', type: 'German', distance_km: 0 }],
    nearby_attractions: [{ name: 'Marienplatz', type: 'Square', distance_km: 1.5 }],
    is_rainy_day_alt: true,
    phase: 'munich',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-marienplatz',
    trip_id: 'trip-alps-2026',
    title: 'Marienplatz & Glockenspiel',
    title_he: 'מריינפלץ וגלוקנשפיל',
    description: "Munich's central square with the famous Glockenspiel — 32 life-size mechanical figures performing daily.",
    description_he: 'כיכר המרכזית של מינכן עם הגלוקנשפיל — 32 דמויות מכניות בגודל טבעי מופיעות כל יום.',
    emoji: '🏛️',
    location_name: 'Munich City Center',
    region: 'Bavaria',
    country: 'Germany',
    lat: 48.1374,
    lng: 11.5754,
    google_maps_url: 'https://maps.google.com/?q=Marienplatz+Munich',
    website: 'https://www.muenchen.de',
    youtube_url: 'https://www.youtube.com/watch?v=BCuJpd7Trkw',
    waze_url: 'https://waze.com/ul?ll=48.1374,11.5754&navigate=yes',
    duration_minutes: 90,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'any-weather',
    price_level: 'free',
    price_estimate: 'חינם',
    booking_required: false,
    booking_url: null,
    tips: 'גלוקנשפיל ב-11:00, 12:00, ו-17:00. הגיעו 10 דקות מוקדם.',
    family_notes: 'הדמויות המכניות מרתקות ילדים מכל גיל.',
    tags: ['urban', 'free', 'kids', 'culture', 'Munich'],
    images: [],
    google_rating: 4.6,
    google_review_count: 52000,
    tripadvisor_rating: 4.6,
    nearby_restaurants: [{ name: 'Hofbräuhaus', type: 'Bavarian', distance_km: 0.4 }],
    nearby_attractions: [{ name: 'Frauenkirche', type: 'Cathedral', distance_km: 0.3 }],
    is_rainy_day_alt: false,
    phase: 'munich',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-nymphenburg',
    trip_id: 'trip-alps-2026',
    title: 'Nymphenburg Palace & Gardens',
    title_he: 'ארמון נימפנבורג וגניו',
    description: 'The summer residence of Bavarian royalty — 200 hectares of baroque gardens. Children under 18 enter free!',
    description_he: 'מעון הקיץ של משפחת המלוכה — 200 דונם של גנים בארוקיים. ילדים מתחת לגיל 18 חינם!',
    emoji: '🏯',
    location_name: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    lat: 48.1582,
    lng: 11.5033,
    google_maps_url: 'https://maps.google.com/?q=Nymphenburg+Palace+Munich',
    website: 'https://www.schloss-nymphenburg.de',
    youtube_url: 'https://www.youtube.com/watch?v=7tEH5GBVAhY',
    waze_url: 'https://waze.com/ul?ll=48.1582,11.5033&navigate=yes',
    duration_minutes: 150,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'mixed',
    weather_suitability: 'any-weather',
    price_level: '€',
    price_estimate: '€15 מבוגר, חינם מתחת לגיל 18',
    booking_required: false,
    booking_url: null,
    tips: 'הגנים תמיד חינם. השכירו אופניים בכניסה.',
    family_notes: 'ילדים מתחת לגיל 18 חינם לגמרי!',
    tags: ['history', 'gardens', 'kids', 'free for kids', 'Munich'],
    images: [],
    google_rating: 4.7,
    google_review_count: 19500,
    tripadvisor_rating: 4.7,
    nearby_restaurants: [{ name: 'Schlosscafé', type: 'Café', distance_km: 0.2 }],
    nearby_attractions: [{ name: 'BMW Museum', type: 'Museum', distance_km: 3 }],
    is_rainy_day_alt: false,
    phase: 'munich',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
export const SEED_DAYS: ItineraryDay[] = [
  {
    id: 'day-1',
    trip_id: 'trip-alps-2026',
    date: '2026-08-18',
    day_number: 1,
    label: 'יום הגעה',
    label_en: 'Arrival Day',
    theme: 'נחיתה, איסוף רכבים, נסיעה לפלכאו',
    base_location: 'Sonnberg Ferienanlage, Flachau',
    base_lat: 47.3419,
    base_lng: 13.3891,
    phase: 'transit',
    slots: [
      { id: 's1-1', day_id: 'day-1', activity_id: null, sort_order: 1, start_time: '14:00', end_time: '15:30', custom_note: '✈️ נחיתה במינכן (MUC). איסוף 3 רכבים — הקצו 1.5 שעות.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's1-2', day_id: 'day-1', activity_id: null, sort_order: 2, start_time: '16:00', end_time: '18:30', custom_note: '🚗 נסיעה מינכן → פלכאו (~2.5 שעות דרך A8/A10).', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's1-3', day_id: 'day-1', activity_id: null, sort_order: 3, start_time: '19:00', end_time: null, custom_note: '🏠 צ\'ק-אין ל-Sonnberg Ferienanlage.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: 'קניות במינימרקט של פלכאו — פתוח עד 19:00.' },
    ],
  },
  {
    id: 'day-2',
    trip_id: 'trip-alps-2026',
    date: '2026-08-19',
    day_number: 2,
    label: 'הלשטאט ודכשטיין',
    label_en: 'Hallstatt & Dachstein',
    theme: 'כפר הפיות + קרחון — כל האזור במכה אחת',
    base_location: 'Sonnberg Ferienanlage, Flachau',
    base_lat: 47.3419,
    base_lng: 13.3891,
    phase: 'austria',
    slots: [
      { id: 's2-1', day_id: 'day-2', activity_id: 'act-hallstatt', sort_order: 1, start_time: '08:30', end_time: '12:00', custom_note: 'הגיעו מוקדם לפני ההמונים! ~60 דקות נסיעה.', status: 'planned', travel_time_from_prev_minutes: 60, is_meal: false, meal_suggestion: null },
      { id: 's2-2', day_id: 'day-2', activity_id: null, sort_order: 2, start_time: '12:00', end_time: '13:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🍽️ Seehotel Grüner Baum — פורל טרי מהאגם.' },
      { id: 's2-3', day_id: 'day-2', activity_id: 'act-dachstein', sort_order: 3, start_time: '13:30', end_time: '17:00', custom_note: '15 דקות נסיעה מהלשטאט.', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
      { id: 's2-4', day_id: 'day-2', activity_id: null, sort_order: 4, start_time: '18:30', end_time: null, custom_note: '🚗 חזרה לפלכאו (~55 דקות)', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-3',
    trip_id: 'trip-alps-2026',
    date: '2026-08-20',
    day_number: 3,
    label: 'זלצבורג',
    label_en: 'Salzburg Day',
    theme: 'יום שלם בעיר מוצארט',
    base_location: 'Sonnberg Ferienanlage, Flachau',
    base_lat: 47.3419,
    base_lng: 13.3891,
    phase: 'austria',
    slots: [
      { id: 's3-1', day_id: 'day-3', activity_id: 'act-salzburg', sort_order: 1, start_time: '09:00', end_time: '13:00', custom_note: '~70 דקות נסיעה מפלכאו.', status: 'planned', travel_time_from_prev_minutes: 70, is_meal: false, meal_suggestion: null },
      { id: 's3-2', day_id: 'day-3', activity_id: null, sort_order: 2, start_time: '13:00', end_time: '14:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🍺 Augustiner Bräustübl — אולם בירה ענקי, ידידותי לילדים.' },
      { id: 's3-3', day_id: 'day-3', activity_id: 'act-mirabell', sort_order: 3, start_time: '14:30', end_time: '16:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: 10, is_meal: false, meal_suggestion: null },
      { id: 's3-4', day_id: 'day-3', activity_id: null, sort_order: 4, start_time: '16:00', end_time: '17:00', custom_note: '🍦 טיול ברחוב גטריידגסה — גלידה ועוד גלידה.', status: 'planned', travel_time_from_prev_minutes: 10, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-4',
    trip_id: 'trip-alps-2026',
    date: '2026-08-21',
    day_number: 4,
    label: 'זל אם זה וקפרון',
    label_en: 'Zell am See & Kaprun',
    theme: 'אגם + קרחון — שני ניגודים באותו יום',
    base_location: 'Sonnberg Ferienanlage, Flachau',
    base_lat: 47.3419,
    base_lng: 13.3891,
    phase: 'austria',
    slots: [
      { id: 's4-1', day_id: 'day-4', activity_id: 'act-zell', sort_order: 1, start_time: '09:30', end_time: '13:00', custom_note: '~50 דקות מפלכאו.', status: 'planned', travel_time_from_prev_minutes: 50, is_meal: false, meal_suggestion: null },
      { id: 's4-2', day_id: 'day-4', activity_id: null, sort_order: 2, start_time: '13:00', end_time: '14:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🐟 Seewirt Dreilinden — ארוחה על שפת האגם.' },
      { id: 's4-3', day_id: 'day-4', activity_id: 'act-kitzsteinhorn', sort_order: 3, start_time: '14:30', end_time: '18:00', custom_note: '⚠️ לכו רק אם השמיים בהירים!', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-5',
    trip_id: 'trip-alps-2026',
    date: '2026-08-22',
    day_number: 5,
    label: 'יום פלכאו',
    label_en: 'Flachau Fun Day',
    theme: 'כיף ליד הצימר — אין נסיעות ארוכות',
    base_location: 'Sonnberg Ferienanlage, Flachau',
    base_lat: 47.3419,
    base_lng: 13.3891,
    phase: 'austria',
    slots: [
      { id: 's5-1', day_id: 'day-5', activity_id: 'act-flachau-toboggan', sort_order: 1, start_time: '10:00', end_time: '12:30', custom_note: '10 דקות מהצימר!', status: 'planned', travel_time_from_prev_minutes: 10, is_meal: false, meal_suggestion: null },
      { id: 's5-2', day_id: 'day-5', activity_id: null, sort_order: 2, start_time: '12:30', end_time: '14:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🥩 גסטהאוס מקומי בפלכאו.' },
      { id: 's5-3', day_id: 'day-5', activity_id: null, sort_order: 3, start_time: '14:30', end_time: '17:00', custom_note: '🏊 בריכה / אגם מקומי — יום מנוחה.', status: 'planned', travel_time_from_prev_minutes: 10, is_meal: false, meal_suggestion: null },
      { id: 's5-4', day_id: 'day-5', activity_id: null, sort_order: 4, start_time: '19:00', end_time: null, custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🔥 בי-בי-קיו משפחתי בצימר!' },
    ],
  },
  {
    id: 'day-6',
    trip_id: 'trip-alps-2026',
    date: '2026-08-23',
    day_number: 6,
    label: 'וולפגנגזה',
    label_en: 'Wolfgangsee Day',
    theme: 'אגמות יפים ושקיעה מדהימה',
    base_location: 'Sonnberg Ferienanlage, Flachau',
    base_lat: 47.3419,
    base_lng: 13.3891,
    phase: 'austria',
    slots: [
      { id: 's6-1', day_id: 'day-6', activity_id: null, sort_order: 1, start_time: '10:00', end_time: '13:00', custom_note: '🏊 רחצה ופיקניק ליד אגם מונדזה — ~50 דקות מפלכאו.', status: 'planned', travel_time_from_prev_minutes: 50, is_meal: false, meal_suggestion: null },
      { id: 's6-2', day_id: 'day-6', activity_id: null, sort_order: 2, start_time: '13:00', end_time: '14:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🥪 פיקניק ליד האגם.' },
      { id: 's6-3', day_id: 'day-6', activity_id: 'act-wolfgangsee', sort_order: 3, start_time: '17:30', end_time: '19:30', custom_note: 'השקיעה מדהימה!', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-7',
    trip_id: 'trip-alps-2026',
    date: '2026-08-24',
    day_number: 7,
    label: 'נסיעה למינכן וכימזה',
    label_en: 'Drive to Munich via Chiemsee',
    theme: 'יום מעבר עם עצירה מדהימה בדרך',
    base_location: 'Hotel Motel One München-City, Munich',
    base_lat: 48.1275,
    base_lng: 11.5979,
    phase: 'munich',
    slots: [
      { id: 's7-1', day_id: 'day-7', activity_id: null, sort_order: 1, start_time: '09:00', end_time: '10:00', custom_note: '🧳 ארוחת בוקר, אריזה וצ\'ק-אאוט.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: null },
      { id: 's7-2', day_id: 'day-7', activity_id: 'act-chiemsee', sort_order: 2, start_time: '10:30', end_time: '14:30', custom_note: 'חנו בפריאן אם כימזה וקחו מעבורת לאי.', status: 'planned', travel_time_from_prev_minutes: 90, is_meal: false, meal_suggestion: null },
      { id: 's7-3', day_id: 'day-7', activity_id: null, sort_order: 3, start_time: '15:00', end_time: '16:30', custom_note: '🚗 כימזה → מינכן (~1.5 שעה). צ\'ק-אין למלון.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's7-4', day_id: 'day-7', activity_id: 'act-englischergarten', sort_order: 4, start_time: '17:00', end_time: '19:30', custom_note: 'גולשי האייסבאך — חובה לראות!', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-8',
    trip_id: 'trip-alps-2026',
    date: '2026-08-25',
    day_number: 8,
    label: 'מינכן עיר',
    label_en: 'Munich City Day',
    theme: 'מדע, ארמון, וכיכר מרכזית',
    base_location: 'Hotel Motel One München-City, Munich',
    base_lat: 48.1275,
    base_lng: 11.5979,
    phase: 'munich',
    slots: [
      { id: 's8-1', day_id: 'day-8', activity_id: 'act-deutsches', sort_order: 1, start_time: '09:00', end_time: '13:00', custom_note: 'קנו כרטיסים מראש!', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
      { id: 's8-2', day_id: 'day-8', activity_id: 'act-marienplatz', sort_order: 2, start_time: '13:00', end_time: '14:30', custom_note: 'גלוקנשפיל ב-12:00 — הגיעו 10 דקות מוקדם!', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
      { id: 's8-3', day_id: 'day-8', activity_id: null, sort_order: 3, start_time: '14:30', end_time: '15:30', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🥨 שוק ויקטואלינמרקט — ברייצל ונקניקיות.' },
      { id: 's8-4', day_id: 'day-8', activity_id: 'act-nymphenburg', sort_order: 4, start_time: '16:00', end_time: '18:30', custom_note: 'ילדים מתחת לגיל 18 — חינם!', status: 'planned', travel_time_from_prev_minutes: 25, is_meal: false, meal_suggestion: null },
      { id: 's8-5', day_id: 'day-8', activity_id: null, sort_order: 5, start_time: '19:30', end_time: null, custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🍺 ארוחת ערב אחרונה — Löwenbräukeller.' },
    ],
  },
  {
    id: 'day-9',
    trip_id: 'trip-alps-2026',
    date: '2026-08-26',
    day_number: 9,
    label: 'יום העזיבה',
    label_en: 'Departure Day',
    theme: 'ארוחת בוקר, אריזה, ופרידה',
    base_location: 'Munich Airport (MUC)',
    base_lat: 48.3538,
    base_lng: 11.7861,
    phase: 'transit',
    slots: [
      { id: 's9-1', day_id: 'day-9', activity_id: null, sort_order: 1, start_time: '07:00', end_time: '08:30', custom_note: '☕ ארוחת בוקר אחרונה. אריזה סופית.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: null },
      { id: 's9-2', day_id: 'day-9', activity_id: null, sort_order: 2, start_time: '09:00', end_time: null, custom_note: '🚗 נסיעה לנמל התעופה MUC — ~45 דקות + החזרת רכב.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's9-3', day_id: 'day-9', activity_id: null, sort_order: 3, start_time: null, end_time: null, custom_note: '✈️ המראה הביתה — טיול נפלא! 🎉', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
    ],
  },
]

export const OPTIONAL_ACTIVITIES: Activity[] = [
  {
    id: 'opt-hellbrunn', trip_id: 'trip-alps-2026',
    title: 'Schloss Hellbrunn & Trick Fountains', title_he: 'ארמון הלברון ומזרקות הפתעה',
    description: 'A baroque summer palace with legendary trick fountains that suddenly spray visitors — kids absolutely love getting soaked!',
    description_he: 'ארמון קיץ בארוקי מהמאה ה-17 עם מזרקות הפתעה אגדיות שמרטיבות מבקרים ללא אזהרה — ילדים פשוט מתים על זה! כ-20 דקות מזלצבורג.',
    emoji: '💦', location_name: 'זלצבורג', region: 'זלצבורג', country: 'Austria',
    lat: 47.7621, lng: 13.0601,
    google_maps_url: 'https://maps.google.com/?q=Schloss+Hellbrunn+Salzburg',
    website: 'https://www.hellbrunn.at', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=47.7621%2C13.0601&navigate=yes&zoom=17',
    duration_minutes: 120, difficulty: 'easy', recommended_ages: 'כל הגילאים',
    activity_type: 'outdoor', weather_suitability: 'good-weather',
    price_level: '€€', price_estimate: '€15 מבוגר, €8 ילד — כולל גנים ומזרקות',
    booking_required: false, booking_url: null,
    tips: 'קחו בגדים להחלפה — המזרקות מרטיבות ממש!',
    family_notes: 'אחד הדברים הכי כיפיים לילדים בכל הטיול.',
    tags: ['kids', 'fun', 'outdoor', 'water', 'Salzburg', 'unique'],
    images: [],
    google_rating: 4.6, google_review_count: 22156, tripadvisor_rating: 4.5,
    nearby_restaurants: [], nearby_attractions: [],
    is_rainy_day_alt: false, phase: 'austria',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'opt-hopsiland', trip_id: 'trip-alps-2026',
    title: 'Hopsiland Mountain Playground', title_he: 'הופסילנד — גן משחקים הררי',
    description: 'An incredible mountain playground near Schladming with marble runs, climbing structures, and a cable car.',
    description_he: 'גן משחקים הררי מדהים ליד שלאדמינג — מסלולי כדורים, מבנות טיפוס ורכבל. כ-45 דקות מפלכאו.',
    emoji: '🎪', location_name: 'שלאדמינג', region: 'שטיריה', country: 'Austria',
    lat: 47.3727, lng: 13.7228,
    google_maps_url: 'https://maps.google.com/?q=Hopsiland+Schladming',
    website: 'https://www.planai.at', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=47.3727%2C13.7228&navigate=yes&zoom=17',
    duration_minutes: 180, difficulty: 'easy', recommended_ages: 'גיל 2-14',
    activity_type: 'outdoor', weather_suitability: 'good-weather',
    price_level: '€€', price_estimate: 'רכבל + גן: €18 מבוגר, €12 ילד',
    booking_required: false, booking_url: null,
    tips: 'הגיעו בבוקר.',
    family_notes: 'גן עדן לילדים 2-14!',
    tags: ['kids', 'outdoor', 'adventure', 'playground', 'unique'],
    images: [],
    google_rating: 4.8, google_review_count: 743, tripadvisor_rating: 4.7,
    nearby_restaurants: [], nearby_attractions: [],
    is_rainy_day_alt: false, phase: 'austria',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'opt-olympiapark', trip_id: 'trip-alps-2026',
    title: 'Olympiapark München', title_he: 'פארק האולימפיאדה מינכן',
    description: 'The 1972 Olympic Park with its iconic tent roof architecture, lake, and TV tower.',
    description_he: 'פארק האולימפיאדה של 1972 עם גג האוהל האייקוני, אגם ומגדל TV. כניסה חינם.',
    emoji: '🏟️', location_name: 'מינכן', region: 'בוואריה', country: 'Germany',
    lat: 48.1754, lng: 11.5520,
    google_maps_url: 'https://maps.google.com/?q=Olympiapark+Munich',
    website: 'https://www.olympiapark.de', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=48.1754%2C11.5520&navigate=yes&zoom=17',
    duration_minutes: 120, difficulty: 'easy', recommended_ages: 'כל הגילאים',
    activity_type: 'outdoor', weather_suitability: 'good-weather',
    price_level: 'free', price_estimate: 'פארק — חינם. מגדל TV: €13 מבוגר, €9 ילד',
    booking_required: false, booking_url: null,
    tips: 'שלבו עם BMW Welt.',
    family_notes: 'מרחב פתוח ענקי. האגם מצוין לפיקניק.',
    tags: ['free', 'outdoor', 'Munich', 'kids', 'history', 'relaxed'],
    images: [],
    google_rating: 4.7, google_review_count: 78327, tripadvisor_rating: 4.6,
    nearby_restaurants: [], nearby_attractions: [{ name: 'מוזיאון BMW', type: 'מוזיאון', distance_km: 0.8 }],
    is_rainy_day_alt: false, phase: 'munich',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'opt-residenz', trip_id: 'trip-alps-2026',
    title: 'Munich Residenz Palace', title_he: 'ארמון הרזידנץ מינכן',
    description: 'The largest city palace in Germany — 130 rooms of baroque decoration plus the Treasury with crown jewels.',
    description_he: 'ארמון העיר הגדול ביותר בגרמניה — 130 חדרים בארוקיים וגנזך עם תכשיטי הכתר. ממש ליד מריינפלץ. ילדים מתחת לגיל 18 חינם!',
    emoji: '👑', location_name: 'מינכן', region: 'בוואריה', country: 'Germany',
    lat: 48.1418, lng: 11.5795,
    google_maps_url: 'https://maps.google.com/?q=Munich+Residenz',
    website: 'https://www.residenz-muenchen.de', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=48.1418%2C11.5795&navigate=yes&zoom=17',
    duration_minutes: 150, difficulty: 'easy', recommended_ages: 'גיל 8+',
    activity_type: 'indoor', weather_suitability: 'any-weather',
    price_level: '€€', price_estimate: '€9 מבוגר, חינם מתחת לגיל 18',
    booking_required: false, booking_url: null,
    tips: 'התחילו מהגנזך.',
    family_notes: 'ילדים מתחת לגיל 18 חינם.',
    tags: ['history', 'Munich', 'indoor', 'rainy day', 'free for kids'],
    images: [],
    google_rating: 4.6, google_review_count: 22104, tripadvisor_rating: 4.5,
    nearby_restaurants: [], nearby_attractions: [{ name: 'מריינפלץ', type: 'כיכר', distance_km: 0.5 }],
    is_rainy_day_alt: true, phase: 'munich',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
]

export const EXTRA_ACTIVITIES: Activity[] = [
  {
    id: 'extra-grossglockner', trip_id: 'trip-alps-2026',
    title: 'Grossglockner High Alpine Road', title_he: 'כביש האלפים גרוסגלוקנר',
    description: 'One of the most scenic alpine roads in Europe — 48km with 36 hairpin turns and glacier views.',
    description_he: 'אחד הכבישים ההרריים היפים באירופה — 48 ק"מ עם 36 פניות ונוף לקרחונות. כ-50 דקות מפלכאו.',
    emoji: '🏔️', location_name: 'גרוסגלוקנר', region: 'קרינתיה', country: 'Austria',
    lat: 47.0855, lng: 12.8412,
    google_maps_url: 'https://maps.google.com/?q=Grossglockner+High+Alpine+Road',
    website: 'https://www.grossglockner.at', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=47.0855%2C12.8412&navigate=yes&zoom=17',
    duration_minutes: 240, difficulty: 'easy', recommended_ages: 'כל הגילאים',
    activity_type: 'outdoor', weather_suitability: 'good-weather',
    price_level: '€€', price_estimate: '€38 לרכב',
    booking_required: false, booking_url: null,
    tips: 'לכו רק ביום בהיר לחלוטין.',
    family_notes: 'ילדים מתרגשים מהשלג והנוף.',
    tags: ['scenic', 'driving', 'glacier', 'nature', 'unique', 'Austria'],
    images: [],
    google_rating: 4.8, google_review_count: 8750, tripadvisor_rating: 4.8,
    nearby_restaurants: [], nearby_attractions: [],
    is_rainy_day_alt: false, phase: 'austria',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'extra-bmw', trip_id: 'trip-alps-2026',
    title: 'BMW Welt & Museum', title_he: 'עולם BMW ומוזיאון',
    description: 'BMW Welt is a free futuristic showroom. Next door, the BMW Museum tells the brand history.',
    description_he: 'BMW Welt — מרכז תצוגה עתידני חינמי. ממש לידו מוזיאון BMW עם 40+ רכבים איקוניים.',
    emoji: '🚗', location_name: 'מינכן', region: 'בוואריה', country: 'Germany',
    lat: 48.1772, lng: 11.5563,
    google_maps_url: 'https://maps.google.com/?q=BMW+Welt+Munich',
    website: 'https://www.bmw-welt.com', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=48.1772%2C11.5563&navigate=yes&zoom=17',
    duration_minutes: 150, difficulty: 'easy', recommended_ages: 'גיל 6+',
    activity_type: 'indoor', weather_suitability: 'any-weather',
    price_level: '€', price_estimate: 'BMW Welt — חינם! מוזיאון: €10 מבוגר, €7 ילד',
    booking_required: false, booking_url: null,
    tips: 'BMW Welt חינם לגמרי.',
    family_notes: 'ילדים אוהבים לשבת על המכוניות.',
    tags: ['Munich', 'cars', 'indoor', 'free', 'rainy day', 'unique'],
    images: [],
    google_rating: 4.7, google_review_count: 39091, tripadvisor_rating: 4.6,
    nearby_restaurants: [], nearby_attractions: [{ name: 'פארק האולימפיאדה', type: 'פארק', distance_km: 0.3 }],
    is_rainy_day_alt: true, phase: 'munich',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'extra-hellabrunn', trip_id: 'trip-alps-2026',
    title: 'Hellabrunn Zoo Munich', title_he: 'גן החיות הלאברון מינכן',
    description: 'One of Europe\'s most innovative geo-zoos. Elephants, giraffes, tigers in spacious natural habitats.',
    description_he: "אחד מגני החיות הוותיקים באירופה — חיות לפי יבשת מוצאן. פילים, ג׳ירפות, נמרים.",
    emoji: '🦒', location_name: 'מינכן', region: 'בוואריה', country: 'Germany',
    lat: 48.0969, lng: 11.5539,
    google_maps_url: 'https://maps.google.com/?q=Hellabrunn+Zoo+Munich',
    website: 'https://www.hellabrunn.de', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=48.0969%2C11.5539&navigate=yes&zoom=17',
    duration_minutes: 240, difficulty: 'easy', recommended_ages: 'כל הגילאים',
    activity_type: 'outdoor', weather_suitability: 'good-weather',
    price_level: '€€', price_estimate: '€22 מבוגר, €9 ילד',
    booking_required: false, booking_url: null,
    tips: 'הגיעו בבוקר.',
    family_notes: 'יום שלם של כיף.',
    tags: ['kids', 'animals', 'outdoor', 'Munich', 'family'],
    images: [],
    google_rating: 4.5, google_review_count: 40179, tripadvisor_rating: 4.5,
    nearby_restaurants: [], nearby_attractions: [],
    is_rainy_day_alt: false, phase: 'munich',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
]

export const FUN_ACTIVITIES: Activity[] = [
  {
    id: 'fun-fantasiana', trip_id: 'trip-alps-2026',
    title: 'Fantasiana Erlebnispark', title_he: 'פארק השעשועים פנטסיאנה',
    description: 'One of Austria's largest theme parks with 50+ attractions across 8 themed worlds.',
    description_he: 'אחד מפארקי השעשועים הגדולים באוסטריה עם 50+ אטרקציות ב-8 עולמות תמטיים. חדש 2026: רכבת הרים Helios! ~45 דקות מפלכאו.',
    emoji: '🎢', location_name: 'שטראסוולכן', region: 'זלצבורג', country: 'Austria',
    lat: 47.9847, lng: 13.3133,
    google_maps_url: 'https://maps.google.com/?q=Fantasiana+Erlebnispark+Strasswalchen',
    website: 'https://www.erlebnispark.at', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=47.9847%2C13.3133&navigate=yes&zoom=17',
    duration_minutes: 360, difficulty: 'easy', recommended_ages: 'גיל 2+',
    activity_type: 'outdoor', weather_suitability: 'good-weather',
    price_level: '€€', price_estimate: '€32 מבוגר, €27 ילד. מתחת לגיל 3 חינם.',
    booking_required: false, booking_url: null,
    tips: 'הגיעו בפתיחה (10:00).',
    family_notes: 'יום שלם של כיף! ילדים מגיל 2 עד מתבגרים.',
    tags: ['kids', 'adventure', 'amusement park', 'fun', 'Austria', 'all ages'],
    images: [],
    google_rating: 4.3, google_review_count: 8200, tripadvisor_rating: 4.2,
    nearby_restaurants: [{ name: 'Western Restaurant', type: 'בתוך הפארק', distance_km: 0 }],
    nearby_attractions: [],
    is_rainy_day_alt: false, phase: 'austria',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'fun-wasserwelt-wagrain', trip_id: 'trip-alps-2026',
    title: 'Wasserwelt Amadé Wagrain', title_he: 'פארק המים וואסרוולט ואגריין',
    description: 'A family water park with indoor and outdoor pools, lazy river, turbo slides and toddler area.',
    description_he: 'פארק מים משפחתי בלב הרי זלצבורג — בריכות, תעלת זרם, מגלשת טורבו, Black Hole. ~15 דקות מפלכאו.',
    emoji: '💦', location_name: 'ואגריין', region: 'זלצבורג לנד', country: 'Austria',
    lat: 47.3344, lng: 13.3011,
    google_maps_url: 'https://maps.google.com/?q=Wasserwelt+Amade+Wagrain',
    website: 'https://www.wagrain-kleinarl.at', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=47.3344%2C13.3011&navigate=yes&zoom=17',
    duration_minutes: 240, difficulty: 'easy', recommended_ages: 'כל הגילאים',
    activity_type: 'mixed', weather_suitability: 'any-weather',
    price_level: '€', price_estimate: '€17 מבוגר, €9 ילד. מתחת לגיל 6 חינם.',
    booking_required: false, booking_url: null,
    tips: 'מומלץ ביום גשום. 15 דקות מפלכאו.',
    family_notes: 'מגלשות לכל הגילאים. אזור לילדים קטנים.',
    tags: ['kids', 'water park', 'indoor', 'rainy day', 'slides', 'Austria', 'family'],
    images: [],
    google_rating: 4.3, google_review_count: 1200, tripadvisor_rating: 4.2,
    nearby_restaurants: [], nearby_attractions: [],
    is_rainy_day_alt: true, phase: 'austria',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'fun-therme-erding', trip_id: 'trip-alps-2026',
    title: 'Therme Erding', title_he: 'תרמה ארדינג — פארק המים הגדול בעולם',
    description: 'The world's largest thermal spa with 28 slides including a 365m tube slide, wave pool and VR slide.',
    description_he: 'ספא תרמי הגדול בעולם — 28 מגלשות כולל שפופרת 365 מטר, בריכת גלים ומגלשת VR. 30 דקות ממינכן.',
    emoji: '🌊', location_name: 'ארדינג, בוואריה', region: 'בוואריה', country: 'Germany',
    lat: 48.3167, lng: 11.9,
    google_maps_url: 'https://maps.google.com/?q=Therme+Erding+waterpark',
    website: 'https://www.therme-erding.de', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=48.3167%2C11.9000&navigate=yes&zoom=17',
    duration_minutes: 300, difficulty: 'easy', recommended_ages: 'כל הגילאים',
    activity_type: 'mixed', weather_suitability: 'any-weather',
    price_level: '€€', price_estimate: 'כ-€35 מבוגר, €25 ילד.',
    booking_required: false, booking_url: null,
    tips: 'מגלשת 365 מטר היא ההייליט!',
    family_notes: 'הפארק הגדול ביותר בעולם — ילדים לא מאמינים.',
    tags: ['kids', 'water park', 'indoor', 'rainy day', 'slides', 'Munich', 'unique', 'world record'],
    images: [],
    google_rating: 4.4, google_review_count: 15000, tripadvisor_rating: 4.3,
    nearby_restaurants: [{ name: 'מסעדות בתוך הפארק', type: 'מגוון', distance_km: 0 }],
    nearby_attractions: [{ name: 'נמל התעופה מינכן', type: 'שדה תעופה', distance_km: 5 }],
    is_rainy_day_alt: true, phase: 'munich',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'fun-bavaria-filmstadt', trip_id: 'trip-alps-2026',
    title: 'Bavaria Filmstadt', title_he: 'עיר הסרטים של בוואריה',
    description: 'Behind the scenes of one of Europe\'s largest film studios — stunt shows, 4D cinema, Das Boot submarine.',
    description_he: 'מאחורי הקלעים של אחד מאולפני הסרטים הגדולים באירופה — מופעי סטאנטס, 4D, הצוללת Das Boot.',
    emoji: '🎬', location_name: 'מינכן', region: 'בוואריה', country: 'Germany',
    lat: 48.0833, lng: 11.5167,
    google_maps_url: 'https://maps.google.com/?q=Bavaria+Filmstadt+Munich',
    website: 'https://www.filmstadt.de', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=48.0833%2C11.5167&navigate=yes&zoom=17',
    duration_minutes: 180, difficulty: 'easy', recommended_ages: 'גיל 6+',
    activity_type: 'mixed', weather_suitability: 'any-weather',
    price_level: '€€', price_estimate: '€16 מבוגר, €12 ילד.',
    booking_required: false, booking_url: null,
    tips: 'מופע הסטאנטס הוא ההייליט.',
    family_notes: 'ילדים מגיל 6 נהנים מאוד.',
    tags: ['kids', 'indoor', 'movies', 'Munich', 'unique', 'rainy day'],
    images: [],
    google_rating: 4.3, google_review_count: 6500, tripadvisor_rating: 4.2,
    nearby_restaurants: [], nearby_attractions: [],
    is_rainy_day_alt: true, phase: 'munich',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'fun-superfly-munich', trip_id: 'trip-alps-2026',
    title: 'Superfly Munich', title_he: 'סופרפליי מינכן — פארק טרמפולינות',
    description: 'A 4,000m² indoor trampoline park with ninja course, zip line, and battle bridge.',
    description_he: "פארק טרמפולינות ואתגרים — מסלול נינג׳ה, רוכסן ועוד. 20 דקות ממינכן.",
    emoji: '🤸', location_name: 'מינכן', region: 'בוואריה', country: 'Germany',
    lat: 48.1167, lng: 11.6333,
    google_maps_url: 'https://maps.google.com/?q=Superfly+Munich+trampoline',
    website: 'https://superfly.de/munich', youtube_url: null,
    waze_url: 'https://ul.waze.com/ul?ll=48.1167%2C11.6333&navigate=yes&zoom=17',
    duration_minutes: 120, difficulty: 'easy', recommended_ages: 'גיל 4+',
    activity_type: 'indoor', weather_suitability: 'any-weather',
    price_level: '€€', price_estimate: 'כ-€18-22 לשעה.',
    booking_required: true, booking_url: 'https://superfly.de/munich',
    tips: 'הזמינו מראש.',
    family_notes: "מסלול הנינג׳ה אהוב על גיל 8-14.",
    tags: ['kids', 'indoor', 'rainy day', 'Munich', 'active', 'trampoline', 'teens'],
    images: [],
    google_rating: 4.4, google_review_count: 3200, tripadvisor_rating: 4.3,
    nearby_restaurants: [], nearby_attractions: [],
    is_rainy_day_alt: true, phase: 'munich',
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
]
