import type { Activity, ItineraryDay, Trip } from '@/types'

// ============================================================
// TRIP
// ============================================================
export const SEED_TRIP: Omit<Trip, 'owner_id' | 'pin_hash'> = {
  id: 'trip-alps-2026',
  slug: 'alps-bavaria-2026',
  name: 'Alps & Bavaria Adventure',
  tagline: 'Austria mountains, fairy-tale villages, and Bavarian charm',
  start_date: '2026-08-18',
  end_date: '2026-08-26',
  cover_emoji: '⛰️',
  cover_image_url: null,
  adults_count: 2,
  children_ages: [6, 9, 12],
  travel_style: 'relaxed',
  kid_focused: true,
  nature_first: true,
  is_public: true,
  share_token: 'fam2026alps',
  destinations: [
    { id: 'd1', trip_id: 'trip-alps-2026', name: 'Munich Airport', country: 'Germany', lat: 48.3538, lng: 11.7861, arrival_date: '2026-08-18', departure_date: '2026-08-18', accommodation_name: null, sort_order: 1 },
    { id: 'd2', trip_id: 'trip-alps-2026', name: 'Flachau', country: 'Austria', lat: 47.3398, lng: 13.3895, arrival_date: '2026-08-18', departure_date: '2026-08-24', accommodation_name: 'Alpenchalet Flachau', sort_order: 2 },
    { id: 'd3', trip_id: 'trip-alps-2026', name: 'Munich', country: 'Germany', lat: 48.1351, lng: 11.5820, arrival_date: '2026-08-24', departure_date: '2026-08-26', accommodation_name: 'Hotel Motel One Munich-City', sort_order: 3 },
  ],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

// ============================================================
// ACTIVITIES
// ============================================================
export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'act-hallstatt',
    trip_id: 'trip-alps-2026',
    title: 'Hallstatt Village Walk',
    description: 'Wander through one of the world\'s most photographed villages — a UNESCO Heritage Site clinging to the edge of a turquoise lake. Narrow cobbled lanes, colorful shuttered houses, and the iconic church reflection in the water make this unmissable. The village is tiny and fully walkable; kids love the salt mine history and the funicular up to the Skywalk.',
    emoji: '🏘️',
    location_name: 'Hallstatt',
    region: 'Upper Austria (Salzkammergut)',
    country: 'Austria',
    lat: 47.5623,
    lng: 13.6493,
    google_maps_url: 'https://maps.google.com/?q=Hallstatt+Austria',
    website: 'https://www.hallstatt.net',
    duration_minutes: 180,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: 'free',
    price_estimate: 'Free to walk. Salt mine tour: €34 adult, €17 child',
    booking_required: false,
    booking_url: null,
    tips: 'Arrive before 9am to beat tour bus crowds. Park at the Lahn lot (P1) — it\'s free and a 10-min walk. The lakeside promenade north of the market square is the best photo spot.',
    family_notes: 'Kids aged 6+ can handle the village easily. The salt mine is fascinating for all ages. Bring swimwear — the lake beach near the ferry landing is swimmable.',
    tags: ['scenic', 'kids', 'nature', 'UNESCO', 'lake', 'free', 'photography'],
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1519677584237-752f8853252e?w=800',
    ],
    google_rating: 4.9,
    google_review_count: 21400,
    tripadvisor_rating: 4.8,
    nearby_restaurants: [
      { name: 'Seehotel Grüner Baum', type: 'Austrian cuisine', distance_km: 0.2, google_maps_url: 'https://maps.google.com/?q=Seehotel+Gruner+Baum+Hallstatt' },
      { name: 'Restaurant Zauner', type: 'Café & Bakery', distance_km: 0.1 },
    ],
    nearby_attractions: [
      { name: 'Hallstatt Skywalk', type: 'Viewpoint', distance_km: 1.5 },
      { name: 'Hallstatt Salt Mine', type: 'Historic site', distance_km: 1.8 },
    ],
    is_rainy_day_alt: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-dachstein',
    trip_id: 'trip-alps-2026',
    title: 'Dachstein Cable Car & Mammut Ice Palace',
    description: 'Soar to 2,700m on the Dachstein Seilbahn for breathtaking glacier and mountain panoramas. Inside the glacier, the Mammut Ice Palace is a surreal world of ice sculptures illuminated with colorful LED lights — kids are absolutely mesmerized. The Sky Walk suspension bridge offers heart-pounding views for the braver family members.',
    emoji: '🚡',
    location_name: 'Obertraun',
    region: 'Upper Austria',
    country: 'Austria',
    lat: 47.5112,
    lng: 13.7137,
    google_maps_url: 'https://maps.google.com/?q=Dachstein+Seilbahn+Obertraun',
    website: 'https://www.dachstein-salzkammergut.at',
    duration_minutes: 150,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'mixed',
    weather_suitability: 'any-weather',
    price_level: '€€',
    price_estimate: '€45 adult, €22.50 child (full combo). Cable car only: €25/€12.50',
    booking_required: true,
    booking_url: 'https://www.dachstein-salzkammergut.at/tickets',
    tips: 'Book online 1–2 days ahead. It\'s 0°C inside the ice cave even in August — bring a warm layer for everyone. The view from the top is best before 11am on clear days.',
    family_notes: 'The ice cave is the family highlight — younger kids are wowed by the illuminated sculptures. The Sky Walk is optional and has a small extra charge; not recommended for kids under 5 or anyone afraid of heights.',
    tags: ['adventure', 'kids', 'scenic', 'glacier', 'cable car', 'rainy day ok'],
    images: [
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800',
    ],
    google_rating: 4.7,
    google_review_count: 8200,
    tripadvisor_rating: 4.6,
    nearby_restaurants: [
      { name: 'Bergrestaurant Schönbergalpe', type: 'Mountain restaurant', distance_km: 0.1 },
    ],
    nearby_attractions: [
      { name: 'Hallstatt Village', type: 'Village', distance_km: 6 },
    ],
    is_rainy_day_alt: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-salzburg',
    trip_id: 'trip-alps-2026',
    title: 'Salzburg Old Town & Hohensalzburg Fortress',
    description: 'Explore Mozart\'s birthplace with its magnificent baroque old town, one of Europe\'s best-preserved city centers. The Hohensalzburg Fortress looming over the city is Austria\'s largest fully preserved castle. Stroll Getreidegasse\'s ornate guild signs, cross the Salzach bridges, and watch the city panorama unfold from the hilltop.',
    emoji: '🏰',
    location_name: 'Salzburg',
    region: 'Salzburg',
    country: 'Austria',
    lat: 47.8095,
    lng: 13.0550,
    google_maps_url: 'https://maps.google.com/?q=Salzburg+Old+Town+Austria',
    website: 'https://www.salzburg.info',
    duration_minutes: 300,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'mixed',
    weather_suitability: 'any-weather',
    price_level: '€€',
    price_estimate: 'Fortress: €16 adult, €9.70 child. Old town walking is free.',
    booking_required: false,
    booking_url: null,
    tips: 'Take the funicular up to the fortress — walking is steep and tiring. Combo tickets include the fortress interior. Eat lunch at the Augustiner Bräustübl beer hall (order food from the stalls inside, it\'s very kid-friendly).',
    family_notes: 'Kids can rent audio guides with dedicated children\'s content at the fortress. Mirabell Gardens has a beautiful rose garden and a fountain plaza where kids can run.',
    tags: ['history', 'kids', 'scenic', 'urban', 'culture', 'food', 'rainy day ok'],
    images: [
      'https://images.unsplash.com/photo-1577388051526-e95efca19b29?w=800',
    ],
    google_rating: 4.8,
    google_review_count: 45000,
    tripadvisor_rating: 4.8,
    nearby_restaurants: [
      { name: 'Zum Fidelen Affen', type: 'Austrian', distance_km: 0.4 },
      { name: 'Stiftskeller St. Peter', type: 'Traditional Austrian', distance_km: 0.3 },
    ],
    nearby_attractions: [
      { name: 'Mirabell Palace & Gardens', type: 'Palace', distance_km: 0.8 },
      { name: 'Mozart Birthplace', type: 'Museum', distance_km: 0.2 },
    ],
    is_rainy_day_alt: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-zell',
    trip_id: 'trip-alps-2026',
    title: 'Zell am See Boat Tour & Beach',
    description: 'Glide across the impossibly blue Zellersee on a wooden excursion boat. The 90-minute ring route passes the charming old town, beach clubs, and dramatic mountain backdrops. After the boat, the lakeside promenade leads to a sandy beach with a kids\' paddling area and a grassy lawn perfect for a family picnic.',
    emoji: '⛵',
    location_name: 'Zell am See',
    region: 'Salzburg Land',
    country: 'Austria',
    lat: 47.3244,
    lng: 12.7964,
    google_maps_url: 'https://maps.google.com/?q=Zell+am+See+boat+station',
    website: 'https://www.schifffahrt-zellamsee.at',
    duration_minutes: 210,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: '€€',
    price_estimate: 'Boat tour: €14 adult, €7 child. Beach entry: €5 adult, €2 child.',
    booking_required: false,
    booking_url: null,
    tips: 'Morning departures have glassier water. The 10:00 and 11:00 boats are least crowded. Rent pedal boats at the southern beach for kids (€12/30 min).',
    family_notes: 'The sandy Strandbad Zell am See beach is excellent for families with young children — shallow water entry and a playground right at the water\'s edge.',
    tags: ['lake', 'scenic', 'kids', 'swimming', 'boat', 'beach', 'relaxed'],
    images: [
      'https://images.unsplash.com/photo-1599708153386-a4c52e0c90f9?w=800',
    ],
    google_rating: 4.7,
    google_review_count: 3100,
    tripadvisor_rating: 4.6,
    nearby_restaurants: [
      { name: 'Seewirt Dreilinden', type: 'Lakeside restaurant', distance_km: 0.5 },
    ],
    nearby_attractions: [
      { name: 'Kitzsteinhorn Glacier', type: 'Mountain', distance_km: 15 },
    ],
    is_rainy_day_alt: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-kitzsteinhorn',
    trip_id: 'trip-alps-2026',
    title: 'Kitzsteinhorn Glacier Experience',
    description: 'Austria\'s most accessible year-round glacier rises to 3,029m above Kaprun. Three cable car stages take you to the top where a panorama terrace reveals views of 30+ mountain peaks. The glacier road and Top of Salzburg viewing platform are crowd favorites. Even in August, snow is often present at the summit.',
    emoji: '🏔️',
    location_name: 'Kaprun',
    region: 'Salzburg Land',
    country: 'Austria',
    lat: 47.1933,
    lng: 12.6866,
    google_maps_url: 'https://maps.google.com/?q=Kitzsteinhorn+Kaprun',
    website: 'https://www.kitzsteinhorn.at',
    duration_minutes: 240,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: '€€€',
    price_estimate: '€55 adult, €28 child (full lift ticket)',
    booking_required: false,
    booking_url: null,
    tips: 'Go on a clear weather day only — if it\'s cloudy in the valley the summit may be in cloud. The glacier is at 2,900–3,029m so even in August temperatures can be 5–10°C at the top.',
    family_notes: 'Kids are amazed to touch real snow/glacier ice in summer. The GletscherJet interactive exhibit at mid-station is a great kids stop. Plan 4 hours minimum.',
    tags: ['glacier', 'scenic', 'adventure', 'altitude', 'kids', 'photography'],
    images: [],
    google_rating: 4.6,
    google_review_count: 5800,
    tripadvisor_rating: 4.5,
    nearby_restaurants: [
      { name: 'Restaurant Gipfel', type: 'Mountain restaurant', distance_km: 0.0 },
    ],
    nearby_attractions: [
      { name: 'Kaprun Reservoir', type: 'Lake / Dam', distance_km: 8 },
    ],
    is_rainy_day_alt: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-wolfgangsee',
    trip_id: 'trip-alps-2026',
    title: 'Lake Wolfgangsee Sunset Walk',
    description: 'St. Wolfgang sits on one of the most beautiful lakes in the Salzkammergut — a quieter, more local alternative to Hallstatt. The evening light turns the water gold and pink. Walk the lakeside promenade, visit the pilgrimage church, grab an ice cream at a waterfront café, and watch the mountains reflect in the calm lake.',
    emoji: '🏖️',
    location_name: 'St. Wolfgang am Wolfgangsee',
    region: 'Upper Austria',
    country: 'Austria',
    lat: 47.7395,
    lng: 13.4465,
    google_maps_url: 'https://maps.google.com/?q=St+Wolfgang+Wolfgangsee',
    website: 'https://www.wolfgangsee.at',
    duration_minutes: 90,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: 'free',
    price_estimate: 'Free. Parking €3/hr.',
    booking_required: false,
    booking_url: null,
    tips: 'Golden hour is 7–8pm in August. Park at the main Seepark lot. The Weisses Rössl hotel terrace (book ahead) has the best lakefront view for drinks.',
    family_notes: 'Very easy and relaxed — perfect after a long activity day. The lake is swimmable at the public beach. Kids can feed ducks at the pier.',
    tags: ['lake', 'scenic', 'free', 'sunset', 'relaxed', 'swimming'],
    images: [],
    google_rating: 4.6,
    google_review_count: 5600,
    tripadvisor_rating: 4.5,
    nearby_restaurants: [
      { name: 'Weisses Rössl', type: 'Traditional Austrian', distance_km: 0.1 },
    ],
    nearby_attractions: [
      { name: 'Pilgrimage Church St. Wolfgang', type: 'Church', distance_km: 0.1 },
    ],
    is_rainy_day_alt: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-chiemsee',
    trip_id: 'trip-alps-2026',
    title: 'Herrenchiemsee Palace Island',
    description: 'Ludwig II\'s most extravagant creation — a Versailles-inspired palace on an island in Bavaria\'s largest lake. Take the ferry across, tour the mirrored Hall of Mirrors (grander than Versailles\' in some opinions), and explore the surrounding Alpenpark. The ferry ride itself and the palace park are highlights for kids.',
    emoji: '🏝️',
    location_name: 'Chiemsee, Bavaria',
    region: 'Bavaria',
    country: 'Germany',
    lat: 47.8559,
    lng: 12.3989,
    google_maps_url: 'https://maps.google.com/?q=Herrenchiemsee+Palace',
    website: 'https://www.herrenchiemsee.de',
    duration_minutes: 210,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'mixed',
    weather_suitability: 'any-weather',
    price_level: '€€',
    price_estimate: '€10 adult, €9 child (palace) + €5.50 ferry each way',
    booking_required: false,
    booking_url: null,
    tips: 'Perfect stop on the drive from Austria to Munich. Park at Prien am Chiemsee (free parking) and take the ferry. Allow 3–3.5 hours total. The palace gardens are free and very nice.',
    family_notes: 'Kids enjoy the ferry boat ride and running in the palace gardens. The palace audio tour is engaging for older children (10+). A great lunch stop too.',
    tags: ['history', 'kids', 'scenic', 'palace', 'boat', 'Bavaria'],
    images: [],
    google_rating: 4.7,
    google_review_count: 12000,
    tripadvisor_rating: 4.7,
    nearby_restaurants: [
      { name: 'Inselrestaurant Herrenchiemsee', type: 'Bavarian', distance_km: 0.1 },
    ],
    nearby_attractions: [
      { name: 'Fraueninsel (Nuns Island)', type: 'Island monastery', distance_km: 3 },
    ],
    is_rainy_day_alt: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-englischergarten',
    trip_id: 'trip-alps-2026',
    title: 'English Garden & Eisbach River Surfers',
    description: 'Munich\'s enormous urban park is larger than Central Park and features the unique spectacle of surfers on the artificial wave at Eisbachwelle. Watch expert surfers shred the urban wave, then explore the Chinese Tower beer garden, rent bikes or paddle boats, and let kids splash in the Auer Mühlbach stream.',
    emoji: '🌳',
    location_name: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    lat: 48.1642,
    lng: 11.6050,
    google_maps_url: 'https://maps.google.com/?q=Eisbachwelle+Munich',
    website: 'https://www.muenchen.de/sehenswuerdigkeiten/parks/englischer-garten',
    duration_minutes: 150,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'good-weather',
    price_level: 'free',
    price_estimate: 'Free. Beer garden from €5. Bike rental €12–18/half day.',
    booking_required: false,
    booking_url: null,
    tips: 'The surfers at Eisbachwelle are most active afternoon. The Chinesischer Turm beer garden is kid-friendly with a carousel nearby. Enter from Prinzregentenstraße for the quickest walk to the wave.',
    family_notes: 'Kids adore watching the surfers — it\'s genuinely unexpected and thrilling. The shallow stream (Auer Mühlbach) in the northern park is safe for paddling. Very relaxed way to spend an afternoon.',
    tags: ['free', 'kids', 'nature', 'urban', 'relaxed', 'Munich'],
    images: [],
    google_rating: 4.7,
    google_review_count: 38000,
    tripadvisor_rating: 4.7,
    nearby_restaurants: [
      { name: 'Chinesischer Turm Biergarten', type: 'Beer garden', distance_km: 0.8 },
    ],
    nearby_attractions: [
      { name: 'Haus der Kunst', type: 'Art museum', distance_km: 0.3 },
    ],
    is_rainy_day_alt: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-deutsches',
    trip_id: 'trip-alps-2026',
    title: 'Deutsches Museum',
    description: 'One of the world\'s largest science and technology museums on an island in the Isar River. Over 73,000 exhibits span mining, aviation, ships, chemistry, physics, and space. Kids go wild in the interactive sections. The full-scale submarine, the planetarium, and the live chemistry lab demonstrations are highlights. You truly cannot see it all in one visit.',
    emoji: '🔬',
    location_name: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    lat: 48.1300,
    lng: 11.5837,
    google_maps_url: 'https://maps.google.com/?q=Deutsches+Museum+Munich',
    website: 'https://www.deutsches-museum.de',
    duration_minutes: 240,
    difficulty: 'easy',
    recommended_ages: '5+ recommended',
    activity_type: 'indoor',
    weather_suitability: 'any-weather',
    price_level: '€€',
    price_estimate: '€18 adult, €8 child (6–17). Under 6 free. Planetarium extra.',
    booking_required: true,
    booking_url: 'https://shop.deutsches-museum.de',
    tips: 'Buy tickets online to skip queues. Start at the ship hall (ground floor) — kids love the submarine. Planetarium shows are German-only but the visuals are impressive regardless.',
    family_notes: 'The perfect rainy day museum. Kids aged 6–14 are in their element. The toy train exhibition (level 5) and aviation hall are especially popular. Allow 3–4 hours minimum.',
    tags: ['kids', 'indoor', 'science', 'rainy day', 'learning', 'Munich'],
    images: [],
    google_rating: 4.5,
    google_review_count: 28000,
    tripadvisor_rating: 4.5,
    nearby_restaurants: [
      { name: 'Museumsgaststätte', type: 'German', distance_km: 0.0 },
      { name: 'Café Isarlust', type: 'Café', distance_km: 0.3 },
    ],
    nearby_attractions: [
      { name: 'Marienplatz', type: 'Town square', distance_km: 1.5 },
    ],
    is_rainy_day_alt: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-marienplatz',
    trip_id: 'trip-alps-2026',
    title: 'Marienplatz & Glockenspiel',
    description: 'Munich\'s central square is framed by the stunning neo-Gothic Neues Rathaus. Watch the famous Glockenspiel — 32 life-size figures enacting medieval stories — perform from the tower. Explore the nearby Viktualienmarkt food market, dive into the covered Kaufingerstraße shopping street, and try the famous Hofbräuhaus around the corner.',
    emoji: '🏛️',
    location_name: 'Munich City Center',
    region: 'Bavaria',
    country: 'Germany',
    lat: 48.1374,
    lng: 11.5754,
    google_maps_url: 'https://maps.google.com/?q=Marienplatz+Munich',
    website: 'https://www.muenchen.de/sehenswuerdigkeiten/museen/marienplatz',
    duration_minutes: 90,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'outdoor',
    weather_suitability: 'any-weather',
    price_level: 'free',
    price_estimate: 'Free. Hofbräuhaus meal ~€18/person.',
    booking_required: false,
    booking_url: null,
    tips: 'Glockenspiel performs daily at 11:00, 12:00, and 17:00. Arrive 10 minutes early for a good standing spot. The Frauenkirche twin towers are a 5-minute walk away.',
    family_notes: 'The mechanical figures genuinely delight kids of all ages. After the show, the pedestrian shopping zone is stroller/kid-friendly. The Hofbräuhaus is surprisingly welcoming to families.',
    tags: ['urban', 'free', 'kids', 'culture', 'Munich', 'city center'],
    images: [],
    google_rating: 4.6,
    google_review_count: 52000,
    tripadvisor_rating: 4.6,
    nearby_restaurants: [
      { name: 'Hofbräuhaus', type: 'Traditional Bavarian', distance_km: 0.4 },
      { name: 'Viktualienmarkt food stalls', type: 'Market food', distance_km: 0.3 },
    ],
    nearby_attractions: [
      { name: 'Frauenkirche', type: 'Cathedral', distance_km: 0.3 },
      { name: 'Residenz Museum', type: 'Palace museum', distance_km: 0.5 },
    ],
    is_rainy_day_alt: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'act-nymphenburg',
    trip_id: 'trip-alps-2026',
    title: 'Nymphenburg Palace & Gardens',
    description: 'The summer residence of Bavarian royalty spreads across 200 hectares of baroque formal gardens, English landscaped park, canals, and pavilions. The palace interior is lavishly gilded and filled with royal portraits. Kids under 18 enter the palace free. The grounds include a miniature palace (Amalienburg) and a canal perfect for paddle boating.',
    emoji: '🏯',
    location_name: 'Munich',
    region: 'Bavaria',
    country: 'Germany',
    lat: 48.1582,
    lng: 11.5033,
    google_maps_url: 'https://maps.google.com/?q=Nymphenburg+Palace+Munich',
    website: 'https://www.schloss-nymphenburg.de',
    duration_minutes: 150,
    difficulty: 'easy',
    recommended_ages: 'All ages',
    activity_type: 'mixed',
    weather_suitability: 'any-weather',
    price_level: '€',
    price_estimate: '€15 adult, free under 18. Gardens always free.',
    booking_required: false,
    booking_url: null,
    tips: 'The gardens are always free — even if skipping the palace it\'s worth a visit. Bike rentals at the entrance (€10/hour) make it easy to cover the large grounds. The canal rowing boats are €10/30 min.',
    family_notes: 'Kids under 18 are completely free in the palace. The baroque garden fountains run in summer and are a great photo moment. A café and restaurant are inside the grounds.',
    tags: ['history', 'gardens', 'kids', 'free for kids', 'Munich', 'palace'],
    images: [],
    google_rating: 4.7,
    google_review_count: 19500,
    tripadvisor_rating: 4.7,
    nearby_restaurants: [
      { name: 'Schlosscafé im Palmenhaus', type: 'Café & restaurant', distance_km: 0.2 },
    ],
    nearby_attractions: [
      { name: 'BMW Museum', type: 'Car museum', distance_km: 3 },
      { name: 'Olympiapark', type: 'Park & arena', distance_km: 3.5 },
    ],
    is_rainy_day_alt: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Rainy Day Alternatives
  {
    id: 'act-salzburg-museum',
    trip_id: 'trip-alps-2026',
    title: 'Salzburg Museum & Panorama Museum',
    description: 'When the weather turns grey, Salzburg\'s museums cluster so tightly in the old town you barely need to go outdoors. The Salzburg Museum in the Neue Residenz covers city history with interactive exhibits. Next door, the Panorama Museum houses a stunning circular 360° painting of Salzburg from 1829 — one of the city\'s hidden gems.',
    emoji: '🖼️',
    location_name: 'Salzburg',
    region: 'Salzburg',
    country: 'Austria',
    lat: 47.7999,
    lng: 13.0463,
    google_maps_url: 'https://maps.google.com/?q=Salzburg+Museum',
    website: 'https://www.salzburgmuseum.at',
    duration_minutes: 120,
    difficulty: 'easy',
    recommended_ages: '8+',
    activity_type: 'indoor',
    weather_suitability: 'indoor-only',
    price_level: '€',
    price_estimate: '€9 adult, €3 child',
    booking_required: false,
    booking_url: null,
    tips: 'Combo ticket covers both museums. The panorama painting alone is worth the visit — it\'s remarkably detailed.',
    family_notes: 'Good for older kids who enjoy history. Younger children may find it dry; combine with the Haus der Natur (Natural History Museum) two streets away.',
    tags: ['indoor', 'rainy day', 'history', 'Salzburg', 'museum'],
    images: [],
    google_rating: 4.4,
    google_review_count: 3200,
    tripadvisor_rating: 4.3,
    nearby_restaurants: [],
    nearby_attractions: [
      { name: 'Haus der Natur', type: 'Natural history museum', distance_km: 0.5 },
    ],
    is_rainy_day_alt: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

// ============================================================
// ITINERARY DAYS
// ============================================================
export const SEED_DAYS: ItineraryDay[] = [
  {
    id: 'day-1',
    trip_id: 'trip-alps-2026',
    date: '2026-08-18',
    day_number: 1,
    label: 'Arrival Day',
    theme: 'Travel light — long journey ahead',
    base_location: 'Flachau, Austria',
    base_lat: 47.3398,
    base_lng: 13.3895,
    phase: 'transit',
    slots: [
      { id: 's1-1', day_id: 'day-1', activity_id: null, sort_order: 1, start_time: null, end_time: null, custom_note: '✈️ Land at Munich Airport (MUC). Pick up rental cars — allow 1–1.5 hours.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's1-2', day_id: 'day-1', activity_id: null, sort_order: 2, start_time: null, end_time: null, custom_note: '🚗 Drive Munich → Flachau (~2.5 hours via A8/A10). Scenic from Salzburg.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's1-3', day_id: 'day-1', activity_id: null, sort_order: 3, start_time: null, end_time: null, custom_note: '🏠 Check in to accommodation. Settle in. Light dinner. Early rest.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: 'Grab groceries in Flachau village — Spar supermarket is open until 19:00.' },
    ],
  },
  {
    id: 'day-2',
    trip_id: 'trip-alps-2026',
    date: '2026-08-19',
    day_number: 2,
    label: 'Flachau Valley',
    theme: 'Get your mountain legs',
    base_location: 'Flachau, Austria',
    base_lat: 47.3398,
    base_lng: 13.3895,
    phase: 'austria',
    slots: [
      { id: 's2-1', day_id: 'day-2', activity_id: null, sort_order: 1, start_time: '09:00', end_time: '11:30', custom_note: '🥾 Morning hike in the Flachau valley — easy meadow trail from the gondola base station. No gondola needed.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's2-2', day_id: 'day-2', activity_id: null, sort_order: 2, start_time: '12:00', end_time: '15:00', custom_note: '🌲 Alpinpark Flachau adventure ropes course. Kids aged 6+ have their own kid-friendly section.', status: 'planned', travel_time_from_prev_minutes: 15, is_meal: false, meal_suggestion: null },
      { id: 's2-3', day_id: 'day-2', activity_id: null, sort_order: 3, start_time: '15:30', end_time: '17:00', custom_note: '💧 Reitdorf mountain lake for a swim. Crystal clear alpine water.', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
      { id: 's2-4', day_id: 'day-2', activity_id: null, sort_order: 4, start_time: '19:00', end_time: null, custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🍽️ Dinner at Gasthof Kirchenwirt in Flachau village — great local Schnitzel.' },
    ],
  },
  {
    id: 'day-3',
    trip_id: 'trip-alps-2026',
    date: '2026-08-20',
    day_number: 3,
    label: 'Hallstatt & Dachstein',
    theme: 'UNESCO magic + glacier ice',
    base_location: 'Flachau, Austria',
    base_lat: 47.3398,
    base_lng: 13.3895,
    phase: 'austria',
    slots: [
      { id: 's3-1', day_id: 'day-3', activity_id: 'act-hallstatt', sort_order: 1, start_time: '09:00', end_time: '12:30', custom_note: null, status: 'planned', travel_time_from_prev_minutes: 60, is_meal: false, meal_suggestion: null },
      { id: 's3-2', day_id: 'day-3', activity_id: null, sort_order: 2, start_time: '13:00', end_time: '14:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🍽️ Lunch at Seehotel Grüner Baum lakeside — try the Forelle (trout) caught in the lake.' },
      { id: 's3-3', day_id: 'day-3', activity_id: 'act-dachstein', sort_order: 3, start_time: '14:30', end_time: '17:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
      { id: 's3-4', day_id: 'day-3', activity_id: 'act-wolfgangsee', sort_order: 4, start_time: '17:30', end_time: '19:00', custom_note: 'Optional detour home — adds 30 mins but worth it for sunset.', status: 'planned', travel_time_from_prev_minutes: 40, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-4',
    trip_id: 'trip-alps-2026',
    date: '2026-08-21',
    day_number: 4,
    label: 'Salzburg Day',
    theme: 'Mozart, baroque, and beer gardens',
    base_location: 'Flachau, Austria',
    base_lat: 47.3398,
    base_lng: 13.3895,
    phase: 'austria',
    slots: [
      { id: 's4-1', day_id: 'day-4', activity_id: 'act-salzburg', sort_order: 1, start_time: '09:00', end_time: '13:30', custom_note: null, status: 'planned', travel_time_from_prev_minutes: 70, is_meal: false, meal_suggestion: null },
      { id: 's4-2', day_id: 'day-4', activity_id: null, sort_order: 2, start_time: '13:30', end_time: '14:30', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🍺 Lunch at Augustiner Bräustübl — enormous beer hall, food stalls, very family-friendly.' },
      { id: 's4-3', day_id: 'day-4', activity_id: null, sort_order: 3, start_time: '14:30', end_time: '16:00', custom_note: '🌹 Mirabell Gardens — rose garden + fountain plaza. Kids love running around the geometric hedges.', status: 'planned', travel_time_from_prev_minutes: 10, is_meal: false, meal_suggestion: null },
      { id: 's4-4', day_id: 'day-4', activity_id: null, sort_order: 4, start_time: '16:00', end_time: '17:00', custom_note: '🍦 Getreidegasse stroll — the famous Mozart street with ornate guild signs. Stop at Eisgrotte for gelato.', status: 'planned', travel_time_from_prev_minutes: 10, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-5',
    trip_id: 'trip-alps-2026',
    date: '2026-08-22',
    day_number: 5,
    label: 'Zell am See',
    theme: 'Alpine lake bliss',
    base_location: 'Flachau, Austria',
    base_lat: 47.3398,
    base_lng: 13.3895,
    phase: 'austria',
    slots: [
      { id: 's5-1', day_id: 'day-5', activity_id: 'act-zell', sort_order: 1, start_time: '09:30', end_time: '13:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: 50, is_meal: false, meal_suggestion: null },
      { id: 's5-2', day_id: 'day-5', activity_id: null, sort_order: 2, start_time: '13:00', end_time: '14:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🍽️ Lakeside lunch at Seewirt Dreilinden — fish and chips, lovely terrace.' },
      { id: 's5-3', day_id: 'day-5', activity_id: 'act-kitzsteinhorn', sort_order: 3, start_time: '14:30', end_time: '18:00', custom_note: 'Check weather forecast morning — skip if overcast, glacier views require clear skies.', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-6',
    trip_id: 'trip-alps-2026',
    date: '2026-08-23',
    day_number: 6,
    label: 'Flachau Fun Day',
    theme: 'Relax and play close to home',
    base_location: 'Flachau, Austria',
    base_lat: 47.3398,
    base_lng: 13.3895,
    phase: 'austria',
    slots: [
      { id: 's6-1', day_id: 'day-6', activity_id: null, sort_order: 1, start_time: '10:00', end_time: '12:00', custom_note: '🎿 Flachau Summer Toboggan (Sommerrodelbahn). Kids fav — 1.3km alpine slide. Multiple runs!', status: 'planned', travel_time_from_prev_minutes: 10, is_meal: false, meal_suggestion: null },
      { id: 's6-2', day_id: 'day-6', activity_id: null, sort_order: 2, start_time: '13:00', end_time: '14:30', custom_note: '🐄 Visit to nearby Alm (alpine farm). Feed cows, see cheese-making, buy fresh Käse.', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
      { id: 's6-3', day_id: 'day-6', activity_id: null, sort_order: 3, start_time: '18:00', end_time: null, custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🔥 Family BBQ at the accommodation. Buy meat & veg at the Flachau Spar + local Käse from the Alm.' },
    ],
  },
  {
    id: 'day-7',
    trip_id: 'trip-alps-2026',
    date: '2026-08-24',
    day_number: 7,
    label: 'Drive North + Chiemsee',
    theme: 'Leave Austria with a Bavarian detour',
    base_location: 'Munich, Germany',
    base_lat: 48.1351,
    base_lng: 11.5820,
    phase: 'munich',
    slots: [
      { id: 's7-1', day_id: 'day-7', activity_id: null, sort_order: 1, start_time: '09:00', end_time: '10:00', custom_note: '🧳 Pack and check out from Flachau accommodation.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's7-2', day_id: 'day-7', activity_id: 'act-chiemsee', sort_order: 2, start_time: '10:30', end_time: '14:30', custom_note: 'Perfect break on the A8 highway — follow signs to Prien am Chiemsee then ferry.', status: 'planned', travel_time_from_prev_minutes: 90, is_meal: false, meal_suggestion: null },
      { id: 's7-3', day_id: 'day-7', activity_id: null, sort_order: 3, start_time: '14:30', end_time: '16:00', custom_note: '🚗 Continue drive to Munich area (~1.5h). Check in to hotel.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's7-4', day_id: 'day-7', activity_id: 'act-englischergarten', sort_order: 4, start_time: '16:30', end_time: '19:00', custom_note: 'Evening walk — Eisbach wave surfers! Enter from Prinzregentenstraße.', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
    ],
  },
  {
    id: 'day-8',
    trip_id: 'trip-alps-2026',
    date: '2026-08-25',
    day_number: 8,
    label: 'Munich City Day',
    theme: 'Science, royalty, and Bavarian beer gardens',
    base_location: 'Munich, Germany',
    base_lat: 48.1351,
    base_lng: 11.5820,
    phase: 'munich',
    slots: [
      { id: 's8-1', day_id: 'day-8', activity_id: 'act-deutsches', sort_order: 1, start_time: '09:00', end_time: '12:30', custom_note: null, status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
      { id: 's8-2', day_id: 'day-8', activity_id: 'act-marienplatz', sort_order: 2, start_time: '13:00', end_time: '14:30', custom_note: 'Glockenspiel at 12:00 (noon) — be there 10 mins early for a spot!', status: 'planned', travel_time_from_prev_minutes: 20, is_meal: false, meal_suggestion: null },
      { id: 's8-3', day_id: 'day-8', activity_id: null, sort_order: 3, start_time: '14:30', end_time: '15:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🥨 Viktualienmarkt lunch — get Obatzda (cheese spread) on a pretzel, fresh Bratwurst, and cold beer.' },
      { id: 's8-4', day_id: 'day-8', activity_id: 'act-nymphenburg', sort_order: 4, start_time: '15:30', end_time: '18:00', custom_note: null, status: 'planned', travel_time_from_prev_minutes: 25, is_meal: false, meal_suggestion: null },
      { id: 's8-5', day_id: 'day-8', activity_id: null, sort_order: 5, start_time: '19:00', end_time: null, custom_note: null, status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: '🍺 Final dinner at a traditional Brauhaus — try Löwenbräukeller or Augustiner an der Frauenkirche.' },
    ],
  },
  {
    id: 'day-9',
    trip_id: 'trip-alps-2026',
    date: '2026-08-26',
    day_number: 9,
    label: 'Departure Day',
    theme: 'Last coffee, safe flight home',
    base_location: 'Munich Airport (MUC)',
    base_lat: 48.3538,
    base_lng: 11.7861,
    phase: 'transit',
    slots: [
      { id: 's9-1', day_id: 'day-9', activity_id: null, sort_order: 1, start_time: '07:00', end_time: '08:30', custom_note: '☕ Hotel breakfast and final pack. Check out by 11am at latest.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: true, meal_suggestion: null },
      { id: 's9-2', day_id: 'day-9', activity_id: null, sort_order: 2, start_time: '09:00', end_time: null, custom_note: '🚗 Drive to MUC airport. Allow 45–60 minutes + 30 min buffer for car return.', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
      { id: 's9-3', day_id: 'day-9', activity_id: null, sort_order: 3, start_time: null, end_time: null, custom_note: '✈️ Fly home. What an adventure! 🎉', status: 'planned', travel_time_from_prev_minutes: null, is_meal: false, meal_suggestion: null },
    ],
  },
]
